import JSZip from "jszip";
import type { ScreenCode } from "@/lib/ai/pipeline";

interface BriefScreen {
  id: string;
  name: string;
  type: string;
  purpose: string;
  sections?: string[];
  primary_action?: string;
}

export function briefToMarkdown(
  brief: Record<string, unknown>,
  screenCodes: ScreenCode[]
): string {
  const today = new Date().toISOString().split("T")[0];
  const lines: string[] = [];
  const appName = (brief.app_name as string) || "App";

  lines.push(`# ${appName} — Screen Specification`);
  lines.push("", `*Generated by VibeKit on ${today}*`);

  // Design decisions
  lines.push("", "## Design Decisions");
  lines.push("");
  lines.push(`- **App Type:** ${brief.app_type}`);
  lines.push(`- **Layout:** ${brief.layout_pattern}`);
  lines.push(`- **Navigation:** ${brief.nav_model}`);
  lines.push(`- **Content Relationship:** ${brief.content_relationship}`);
  lines.push(`- **Mutation Model:** ${brief.mutation_model}`);
  lines.push(`- **Density:** ${brief.density}`);
  lines.push(`- **Personality:** ${brief.personality}`);

  if (brief.design_notes) {
    lines.push("", `**Design Notes:** ${brief.design_notes}`);
  }

  // Screens
  lines.push("", "## Screens");
  const screens = (brief.screens as BriefScreen[]) || [];
  for (const screen of screens) {
    lines.push("");
    lines.push(`### ${screen.name}`);
    lines.push(`- **ID:** ${screen.id}`);
    lines.push(`- **Type:** ${screen.type}`);
    lines.push(`- **Purpose:** ${screen.purpose}`);
    if (screen.primary_action) {
      lines.push(`- **Primary Action:** ${screen.primary_action}`);
    }
    if (screen.sections && screen.sections.length > 0) {
      lines.push(`- **Sections:** ${screen.sections.join(", ")}`);
    }
  }

  // Screen code files
  if (screenCodes.length > 0) {
    lines.push("", "## Generated Screens");
    lines.push("");
    for (const sc of screenCodes) {
      lines.push(`- \`${sc.id}.jsx\` — ${sc.name} (${sc.type})`);
    }
  }

  // Navigation
  const navItems = brief.nav_items as Array<{ label: string; icon: string; screen: string }>;
  if (navItems && navItems.length > 0) {
    lines.push("", "## Navigation");
    lines.push("");
    for (const item of navItems) {
      lines.push(`- **${item.label}** (icon: ${item.icon}) → screen: ${item.screen}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

export function briefToClaudeMd(
  brief: Record<string, unknown>,
  skinName: string
): string {
  const appName = (brief.app_name as string) || "App";
  const screens = (brief.screens as BriefScreen[]) || [];
  const pageCount = screens.filter(s => s.type === "page").length;

  return `# ${appName} Design System

## CSS Variable System

All colors use CSS variables via helper functions:

\`\`\`jsx
const h = (v) => \`hsl(var(\${v}))\`;
const ha = (v, a) => \`hsl(var(\${v}) / \${a})\`;
\`\`\`

Available variables:
- \`--bg\`, \`--fg\` — page background and text
- \`--primary\`, \`--primary-fg\` — primary actions and their text
- \`--muted\`, \`--muted-fg\` — muted backgrounds and secondary text
- \`--card\`, \`--card-fg\` — card surfaces
- \`--border\` — borders and dividers
- \`--ring\` — focus rings
- \`--destructive\`, \`--destructive-fg\` — danger/delete actions
- \`--accent\`, \`--accent-fg\` — accent highlights

## Design Decisions

- **App Type:** ${brief.app_type}
- **Layout:** ${brief.layout_pattern}
- **Navigation:** ${brief.nav_model}
- **Content Relationship:** ${brief.content_relationship}
- **Mutation Model:** ${brief.mutation_model}
- **Density:** ${brief.density}
- **Personality:** ${brief.personality}
- **Skin:** ${skinName}

## App Structure

The app uses **${brief.nav_model}** navigation with ${pageCount} main screens.

See \`SCREEN_SPEC.md\` for the full screen-by-screen specification.

## Rules

- ALWAYS use CSS variables via h()/ha() helpers — NEVER use raw Tailwind colors
- Match the ${brief.density} density in all layouts
- Follow the ${brief.personality} personality in typography and copy
- Use \`data-navigate="screen-id"\` for navigation between screens
- Use \`data-overlay="screen-id"\` for dialogs/sheets
`;
}

export async function exportPipelineZip(
  brief: Record<string, unknown>,
  screenCodes: ScreenCode[],
  skinName: string
): Promise<Blob> {
  const zip = new JSZip();
  const folder = zip.folder("vibekit-export")!;

  folder.file("CLAUDE.md", briefToClaudeMd(brief, skinName));
  folder.file("SCREEN_SPEC.md", briefToMarkdown(brief, screenCodes));

  // Screen code files
  const screensFolder = folder.folder("screens")!;
  for (const sc of screenCodes) {
    screensFolder.file(`${sc.id}.jsx`, sc.code);
  }

  // Design brief JSON
  folder.file("design-brief.json", JSON.stringify(brief, null, 2));

  return zip.generateAsync({ type: "blob" });
}
