import JSZip from "jszip";
import type { ScreenSpec } from "./spec-types";
import { specToMarkdown } from "./spec-to-markdown";
import { specToClaudeMd } from "./spec-to-claude-md";

const README_CONTENT = `# VibeKit Export

This package was generated by [VibeKit](https://vibekit.dev) — a design companion for AI-powered app building.

## What's Included

- **CLAUDE.md** — Design system rules and app structure instructions for your AI coding tool
- **SCREEN_SPEC.md** — Detailed breakdown of every screen, component, and interaction

## Getting Started

1. **Install VibeKit components** into your Next.js project:

   \`\`\`bash
   # Clone the VibeKit repository
   git clone https://github.com/your-org/vibekit.git

   # Copy the component library into your project
   cp -r vibekit/components/ your-project/components/
   cp -r vibekit/styles/ your-project/styles/
   \`\`\`

2. **Place CLAUDE.md** in your project root so your AI coding tool picks it up automatically.

3. **Reference SCREEN_SPEC.md** when prompting your AI tool to build screens:
   - "Build the Tasks page as described in SCREEN_SPEC.md"
   - Or paste specific sections into your prompts

## Tips

- The CLAUDE.md file includes both the VibeKit design system rules and your app-specific structure.
- Keep CLAUDE.md updated as your app evolves.
- Use the screen spec as a living document — update it as you add or change screens.
`;

export async function exportDesignSystem(
  spec: ScreenSpec,
  skinName: string
): Promise<Blob> {
  const zip = new JSZip();
  const folder = zip.folder("vibekit-export")!;

  folder.file("CLAUDE.md", specToClaudeMd(spec));
  folder.file("SCREEN_SPEC.md", specToMarkdown(spec));
  folder.file("README.md", README_CONTENT);

  return zip.generateAsync({ type: "blob" });
}
