import type { ScreenSpec, Screen } from "./spec-types";
import { describeSection } from "./describe-section";

function renderScreen(screen: Screen): string {
  const lines: string[] = [];

  lines.push(`### ${screen.name}`);

  const meta: string[] = [];
  if (screen.type) meta.push(`Type: ${screen.type}`);
  if (screen.path) meta.push(`Path: \`${screen.path}\``);
  if (screen.layout) meta.push(`Layout: ${screen.layout}`);
  if (meta.length > 0) lines.push(meta.join(" · "));

  lines.push("", screen.description);

  if (screen.openedVia) {
    lines.push(
      "",
      `> Opened via **${screen.openedVia.type}** from **${screen.openedVia.from}**`
    );
  }

  if (screen.sections.length > 0) {
    lines.push("");
    for (const section of screen.sections) {
      lines.push(describeSection(section));
      lines.push("");
    }
  }

  if (screen.emptyState) {
    const es = screen.emptyState;
    const icon = es.icon ? ` (icon: ${es.icon})` : "";
    lines.push(
      `**Empty State:**${icon} "${es.title}" — ${es.description}`
    );
    if (es.action) {
      lines.push(
        `Action: "${es.action.label}" → navigates to ${es.action.navigateTo}`
      );
    }
  }

  return lines.join("\n");
}

export function specToMarkdown(spec: ScreenSpec): string {
  const today = new Date().toISOString().split("T")[0];
  const lines: string[] = [];

  lines.push(`# ${spec.appName} — Screen Specification`);
  lines.push("", `*Generated by VibeKit on ${today}*`);

  // Screens
  lines.push("", "## Screens");
  for (const screen of spec.screens) {
    lines.push("", renderScreen(screen));
  }

  // Navigation
  lines.push("", "## Navigation");
  lines.push("", `Navigation type: **${spec.navigation.type}**`);
  if (spec.navigation.items.length > 0) {
    lines.push("");
    for (const item of spec.navigation.items) {
      lines.push(`- **${item.label}** (icon: ${item.icon}) → screen: ${item.screen}`);
    }
  }

  // Interaction Patterns
  lines.push("", "## Interaction Patterns");
  const transitions = spec.interactions?.transitions ?? {};
  const transitionEntries = Object.entries(transitions);
  if (transitionEntries.length > 0) {
    lines.push("");
    for (const [key, description] of transitionEntries) {
      lines.push(`- **${key}**: ${description}`);
    }
  } else {
    lines.push("", "No custom interaction patterns defined.");
  }

  lines.push("");
  return lines.join("\n");
}
