import {
  AlertCircle,
  Archive,
  BarChart,
  Bell,
  Calendar,
  Check,
  CheckCircle,
  Clock,
  Cloud,
  Code,
  Copy,
  CreditCard,
  Download,
  Edit,
  Eye,
  File,
  FileText,
  Filter,
  Folder,
  Globe,
  Heart,
  Home,
  Image,
  Inbox,
  Key,
  Layers,
  Layout,
  Link,
  List,
  Lock,
  LogOut,
  Mail,
  Map,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  PenTool,
  Phone,
  Plus,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Sun,
  Tag,
  Target,
  Trash,
  TrendingUp,
  Upload,
  User,
  Users,
  Video,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "alert-circle": AlertCircle,
  archive: Archive,
  "bar-chart": BarChart,
  bell: Bell,
  calendar: Calendar,
  check: Check,
  "check-circle": CheckCircle,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  copy: Copy,
  "credit-card": CreditCard,
  download: Download,
  edit: Edit,
  eye: Eye,
  file: File,
  "file-text": FileText,
  filter: Filter,
  folder: Folder,
  globe: Globe,
  heart: Heart,
  home: Home,
  image: Image,
  inbox: Inbox,
  key: Key,
  layers: Layers,
  layout: Layout,
  link: Link,
  list: List,
  lock: Lock,
  "log-out": LogOut,
  logout: LogOut,
  mail: Mail,
  map: Map,
  "message-circle": MessageCircle,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  package: Package,
  "pen-tool": PenTool,
  phone: Phone,
  plus: Plus,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  star: Star,
  sun: Sun,
  tag: Tag,
  target: Target,
  trash: Trash,
  "trending-up": TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  zap: Zap,
};

export function getLucideIcon(name?: string): LucideIcon | undefined {
  if (!name) return undefined;
  const normalized = name.toLowerCase().replace(/\s+/g, "-");
  return iconMap[normalized] || iconMap[name] || undefined;
}
